---
language: C

services:
     - docker

jobs:
     include:
          - script: make build
          - script: make test
          - stage: Github Release
            script: echo "Deploying to github releases"
            deploy:
                 provider: releases
                 api_key: $GITHUB_OAUTH_TOKEN
                 skip_cleanup: true
                 on:
                      tags: true
